### PR TITLE
ETC2 support

### PR DESCRIPTION
**Pull request by K0lb3**
Adds support for ETC2,ETC2A,ETC1S,ETC2AS by using modified crunch files based on https://github.com/Unity-Technologies/crunch/tree/unity

### CODE REVIEW

**Comment by jleclanche** [comment]
I have cleaned up your PR and reduced the diff noise by standardizing on a clang-format first.

However, the tests are failing…

**Comment by jleclanche** [comment]
By the way, please don't modify setup.cfg in PRs. That is done at release time (I'll do one once this lands).

**Comment by jleclanche** [comment]
Fixed the compile errors, now just the failing test.

**Comment by K0lb3** [comment]
Thanks o/

It was compiling fine on my windows system,
that's why I thought it's alright.

A friend who uses mac had to use
`#define malloc_usable_size malloc_size`
to compile it.


It's a bit strange that it fails the test.
At least I can say that the results look fine,
based on the image I got in various datamines.
* The Alchemist Code (some ETC crunched images)
* Langrisser Mobile (some ETC crunched images)
* Disgea RPG (ETC2 crunched)).

**Comment by jleclanche** [comment]
Can you take a look at the test images before & after and check that they're still good?

I'm very wary of merging something that has binary differences on a lossless format, but it might be the previous behaviour was incorrect. Either way if that's the case the tests need to be updated.

**Comment by K0lb3** [comment]
```python
def CompareImages(typ):
	crn_path = get_resource("%s.crn"%typ)
	img_path = get_resource("%s.png"%typ)
	if typ == 'dxt1':
		args = (1, )
	elif typ == 'dxt5':
		args = (3, )


	img_ori = Image.open(img_path)

	data = open(crn_path,'rb').read()
	data = bytes(File(data).decode_level(0))
	img_ex = Image.frombytes('RGBA', img_ori.size, data, 'bcn', args)
	img_ex.save(img_path[:-4]+'_ex.png')
	
	c_ori = img_ori.split()
	c_ex  = img_ex.split()

	for i,channel in enumerate(['Red','Green','Blue','Alpha']):
		print(channel, c_ori[i]==c_ex[i])
```

dxt1_ex
dxt1
dxt5_ex
dxt5

**Comment by K0lb3** [comment]
The images aren't exactly identical.

I compared them via
[online-image-comparison](https://online-image-comparison.com/).

The alpha channel seems to be the biggest issue.

**Comment by K0lb3** [comment]
via compressonator
image

**Comment by K0lb3** [comment]
..........
I just noticed......that the crunch from unity somehow has problems with the test files.

e.g.
[crunch_x64](https://github.com/Unity-Technologies/crunch/blob/unity/bin/crunch_x64.exe) 
converts the dxt5 to
image

The original crunch works fine.
So I guess........that the original crunch code should be used instead of the one from unity, just with the addition of ETC/2 conversion.

I will work through it today,

**Comment by K0lb3** [comment]
Alright, managed to fix it.
Both tests are passed and ETC2 works too.

**Comment by K0lb3** [comment]
```python
class Format(IntEnum):
	"""
	Crunch format (what block-compressed texture format this decodes to)
	"""

	Invalid = -1
	DXT1 = 0
	DXT3 = 1
	DXT5 = 2

	# Various DXT5 derivatives
	DXT5_CCxY = 3 # Luma-chroma
	DXT5_xGxR = 4 # Swizzled 2-component
	DXT5_xGBR = 5 # Swizzled 3-component
	DXT5_AGBR = 6 # Swizzled 4-component

	# ATI 3DC and X360 DXN
	DXN_XY = 7
	DXN_YX = 8

	# DXT5 Alpha block only
	DXT5A = 9

	ETC1 = 10
	ETC2 = 11
	ETC2A = 12
	ETC1S = 13
	ETC2AS = 14
```
in decrunch.pyx has to be changed too,
the current version is missing the last 4 entries.

**Comment by jleclanche** [comment]
Can you update it?

**Comment by K0lb3** [comment]
Ah,
I really have no real experience with the compiler settings in crn_decomp.cpp.

A friend figured out that mac requires
```
#define malloc_usable_size malloc_size
```

The way I changed it just now doesn't work -.-'

**Comment by jleclanche** [comment]
Will merge this tomorrow.

**Comment by K0lb3** [comment]
Alright 👌

**Pull request merged**
